version: '3.8'

services:
  claude-coder-agent:
    build:
      context: .
      dockerfile: Dockerfile.claude_coder
    container_name: claude-coder-agent
    volumes:
      # Mount the current codebase for scanning
      - .:/app/codebase:ro
      # Mount scans directory for output
      - ./scans:/app/scans
      # Mount logs directory
      - ./logs:/app/logs
      # Mount data directory
      - ./data:/app/data
    environment:
      - CLAUDE_API_KEY=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
      - DEEPSEEK_API_KEY=sk-90e0dd863b8c4e0d879a02851a0ee194
      - PYTHONPATH=/app
    working_dir: /app/codebase
    command: ["python", "/app/claude_coder_docker.py"]
    restart: unless-stopped
    networks:
      - claude-coder-network

  # Optional: Add a web interface for viewing scan results
  claude-coder-web:
    image: nginx:alpine
    container_name: claude-coder-web
    ports:
      - "8080:80"
    volumes:
      - ./scans:/usr/share/nginx/html/scans:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - claude-coder-agent
    networks:
      - claude-coder-network
    profiles:
      - web

networks:
  claude-coder-network:
    driver: bridge

volumes:
  scans:
  logs:
  data: 